services:
  - type: web
    name: virtual-lab-physics
    env: node
    plan: free
    region: singapore  # Atau oregon, frankfurt sesuai preferensi
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false  # Set manually di Render dashboard
      - key: MONGODB_URI  
        sync: false  # Set manually di Render dashboard
      - key: JWT_SECRET
        sync: false  # Set manually di Render dashboard